using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using RestaurantPOS.Domain.Entities;

namespace RestaurantPOS.Infrastructure.Persistence.Configurations;

internal sealed class MenuItemConfiguration : IEntityTypeConfiguration<MenuItem>
{
    public void Configure(EntityTypeBuilder<MenuItem> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("MenuItems");

        builder.HasKey(m => m.Id);

        // Ids are generated by the domain, not the database.
        builder.Property(m => m.Id).ValueGeneratedNever();

        builder.Property(m => m.Name)
            .IsRequired()
            .HasMaxLength(MenuItem.NameMaxLength);

        builder.HasIndex(m => m.Name).IsUnique();

        builder.Property(m => m.Category)
            .IsRequired()
            .HasMaxLength(MenuItem.CategoryMaxLength);

        builder.Property(m => m.Price).IsRequired();

        builder.Property(m => m.IsActive).IsRequired();
    }
}