using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using RestaurantPOS.Domain.Entities;

namespace RestaurantPOS.Infrastructure.Persistence.Configurations;

internal sealed class MenuItemConfiguration : IEntityTypeConfiguration<MenuItem>
{
    public void Configure(EntityTypeBuilder<MenuItem> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("MenuItems");

        builder.HasKey(m => m.Id);

        // Ids are generated by the domain, not the database.
        builder.Property(m => m.Id).ValueGeneratedNever();

        builder.Property(m => m.Name)
            .IsRequired()
            .HasMaxLength(MenuItem.NameMaxLength);

        builder.HasIndex(m => m.Name).IsUnique();

        builder.Property(m => m.Category)
            .IsRequired()
            .HasMaxLength(MenuItem.CategoryMaxLength);

        builder.Property(m => m.IsActive).IsRequired();

        builder.Metadata
            .FindNavigation(nameof(MenuItem.Variants))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        builder.HasMany(m => m.Variants)
            .WithOne()
            .HasForeignKey(v => v.MenuItemId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class MenuItemVariantConfiguration : IEntityTypeConfiguration<MenuItemVariant>
{
    public void Configure(EntityTypeBuilder<MenuItemVariant> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("MenuItemVariants");

        builder.HasKey(v => v.Id);
        builder.Property(v => v.Id).ValueGeneratedNever();

        builder.Property(v => v.Name).HasMaxLength(MenuItemVariant.NameMaxLength);

        builder.Property(v => v.Price).IsRequired();
        builder.Property(v => v.SortOrder).IsRequired();

        builder.HasIndex(v => v.MenuItemId);
    }
}

internal sealed class MenuCategoryConfiguration : IEntityTypeConfiguration<MenuCategory>
{
    public void Configure(EntityTypeBuilder<MenuCategory> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("MenuCategories");

        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).ValueGeneratedNever();

        builder.Property(c => c.Name)
            .IsRequired()
            .HasMaxLength(MenuCategory.NameMaxLength);

        builder.HasIndex(c => c.Name).IsUnique();
    }
}