using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using RestaurantPOS.Domain.Entities;

namespace RestaurantPOS.Infrastructure.Persistence.Configurations;

internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable("Users");

        builder.HasKey(u => u.Id);

        // Ids are generated by the domain, not the database.
        builder.Property(u => u.Id).ValueGeneratedNever();

        builder.Property(u => u.Username)
            .IsRequired()
            .HasMaxLength(User.UsernameMaxLength);

        // Usernames are normalised to lower case by the aggregate, so a plain unique index is
        // enough to make lookups case-insensitive without relying on collation.
        builder.HasIndex(u => u.Username).IsUnique();

        builder.Property(u => u.FullName)
            .IsRequired()
            .HasMaxLength(User.FullNameMaxLength);

        builder.Property(u => u.Email)
            .HasMaxLength(User.EmailMaxLength);

        builder.Property(u => u.PasswordHash)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(u => u.ApprovalPinHash)
            .HasMaxLength(200);

        builder.Property(u => u.Role)
            .IsRequired()
            .HasConversion<int>();

        builder.Property(u => u.IsActive).IsRequired();
        builder.Property(u => u.MustChangePassword).IsRequired();
        builder.Property(u => u.IsSystemAdmin).IsRequired();

        // The aggregate exposes read-only views over private lists, so EF must read and write
        // the backing fields rather than the properties.
        builder.Metadata
            .FindNavigation(nameof(User.ModulePermissions))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        builder.Metadata
            .FindNavigation(nameof(User.RefreshTokens))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);

        builder.HasMany(u => u.ModulePermissions)
            .WithOne()
            .HasForeignKey(p => p.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasMany(u => u.RefreshTokens)
            .WithOne()
            .HasForeignKey(t => t.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}